site_name: AI Agentic Bootcamp

copyright: Copyright &copy; 2025 KT AX Build Task Force. All rights reserved.

extra:
  homepage: https://kt-ax-build.github.io/bootcamp/

theme:
  name: material
  highlightjs: true
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Public Sans"
    code: "Roboto Mono"
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;'
  - tags
  - autorefs
  - include-markdown
  - open-in-new-tab

nav:
  - Introduction:
    - index.md
  - Curriculum:
    - doc-introduction/course-overview.md
  - AX Build Agile:
    # - doc-agile/index.md
    - Agile Build Agile 소개: doc-agile/ax-build-intro.md
  - Agile 기반 AI 활용:
    - Agile & AI Agentic Coding 동행: doc-agile-ai-lead/agile-ai-coding.md
    - Agile 환경 AI Lead 개발 PoC: doc-agile-ai-lead/ai-lead-poc.md
    - "Discover: 요구사항 명세(PRD) 기반 분석/설계": doc-agile-ai-lead/discover-prd.md
    - "Deliver: Planning & Design": doc-agile-ai-lead/deliver-planning.md
    - "Deliver: Develop & Test": doc-agile-ai-lead/deliver-develop.md
  - AI Agentic Coding 실습:
    - 개발 환경 구성: doc-hands-on/dev-environment.md
    - MCP 연동 환경 구성: doc-hands-on/mcp-setup.md
    - 실습 과제 수행: doc-hands-on/practice-tasks.md
