site_name: AI Agentic Bootcamp
# site_url: https://kt-ax-build.github.io/bootcamp/

copyright: Copyright &copy; 2025 KT AX Build Task Force. All rights reserved.

# extra:
#   homepage: https://kt-ax-build.github.io/bootcamp/

theme:
  name: material
  highlightjs: true
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Hanna"
    code: "Roboto Mono"
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.indexes
    - navigation.path
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.tooltips

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - autorefs
  - awesome-nav
  - include-markdown
  - macros:
      module_name: main
  - open-in-new-tab
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
  - search:
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;'
  - tags
